### ISSUE TITLE
Le nombre de kills ne monte pas correctement - Prio low

### ISSUE THREAD

**Issue by gtedavid** [efrei-craft/Ludos#32]
Nombre de Killstreak monte correctement 
Mais pas le nombre de kills de l'équipe (un décalage apparait)

**Comment by Mathu-lmn** [comment]
Je n'ai pas ce soucis

**Comment by Mathu-lmn** [comment]
@Niilyx tu aurais plus d'infos ? Ou on delete ? (ça fait 1 an et demi)
